### ISSUE TITLE
Playground error=unauthorized_client

### ISSUE THREAD

**Issue by Alexanderstephengreenwood** [bshaffer/oauth2-server-php#660] opened 2015-10-28 10:08 UTC
Hello,

I've been playing around with this oauth server that I'm considering to integrate in replacement to my current basic API server that needs securing.

I'm blocking on an issue while testing the authorize and token processes on Google play and with postman where I'm getting an "error=unauthorized_client&error_description=The+grant+type+is+unauthorized+for+this+client_id"

After a bit of research I've found out that I need to configure the server for implicit grant type. The how to set the grant type to true is explained in these page.

I'm struggling with the settings. I managed to set "allow" implicit to "True" but don't understand how and where I need to set the storage and the handle.
```
$storage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));
$server = new OAuth2\Server($storage, array('allow_implicit' => true));

$server->handleAuthorizeRequest(OAuth2\Request::createFromGlobals())->send();
```
Help on these steps would be much appreciated.

Regards,
alex

**Comment by Kami-no** [comment] 2015-10-28 23:31
Check #659

**Comment by bshaffer** [comment] 2015-10-29 21:26
closing as duplicate of #659

**Closed by bshaffer** 2015-10-29 21:26 UTC
